nextcord/nextcord-ext-menus

README.md, nextcord/ext/menus/__init__.py
Added a class `ButtonMenu` that extends `Menu` for easily implementing menus with button components.
I have also added a helper class `ButtonMenuPages` which is the button component equivalent to `MenuPages`.
Discord bot for testing nextcord-ext-menus:
https://gist.github.com/DenverCoder1/b734a220ac108d024228a22772a89cd1
=> Added button component menus

README.md, nextcord/ext/menus/__init__.py, nextcord/ext/menus/menus.py
Added the ability to automatically disable all buttons on timeout or stop by simply passing `disable_buttons_after=True` to the `ButtonMenu` constructor.
=> Added disable_buttons_after kwarg to ButtonMenu

nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/menus.py
Allows inheriting from `ButtonMenuPages` but not inheriting buttons, allowing the developer to use menu page methods with a custom selection of buttons.
**Example code:**
```py
class CustomButtonMenuPages(menus.ButtonMenuPages, inherit_buttons=False):
def __init__(self, source: dict, timeout: int = 60):
super().__init__(source, timeout=timeout, delete_message_after=True)
@nextcord.ui.button(emoji="\N{BLACK LEFT-POINTING TRIANGLE}\N{VARIATION SELECTOR-16}")
async def go_back(self, button, interaction):
if self.current_page == 0:
await self.show_page(self._source.get_max_pages() - 1)
else:
await self.show_checked_page(self.current_page - 1)
@nextcord.ui.button(emoji="\N{BLACK RIGHT-POINTING TRIANGLE}\N{VARIATION SELECTOR-16}")
async def go_next(self, button, interaction):
if …
```
=> Allow `inherit_buttons=False` to skip ButtonMenuPages buttons

nextcord/ext/menus/constants.py, nextcord/ext/menus/menu_pages.py
Modified `MenuPaginationButton` constructor to take any keyword arguments so that when inheriting from `ButtonMenuPages` or customizing the available buttons, the user can add buttons using `MenuPaginationButton()`, thereby using the provided button callback assuming the emojis used are the same.
This change simplifies the code, but also allows users to incorporate `MenuPaginationButton` in their code with `label`, `custom_id`, `row`, etc.
[Additionally, `nextcord.ui.View` was added to the type annotation for send-method kwargs since that is the type for the `view` kwarg.]
May cause breaking changes in rare cases if `MenuPaginationButton` is used in users' code without keywording the emoji and style arguments. There is almost no reason to need to use `MenuPaginationButton` directly …
=> Slight changes to MenuPaginationButton constructor

nextcord/ext/menus/menu_pages.py
Fixes #18 
Previously, `ButtonMenuPages` updates the menu message two times (one to update the content/embed and another to update the view). This PR consolidates the two edits into a single request for efficiency.
The `view` kwarg was added to an override of `_get_kwargs_from_page` so that `ButtonMenuPages` will always make sure the view is updated when editing the menu and there is no need to update the view at the end of the button callback.
* The call to `_disable_unavailable_buttons()` now happens in `show_page()` instead of the Button callback.
* `_get_kwargs_from_page()` for ButtonMenuPages will always include `view` as a key.
=> Combine separate edits into one

README.md
Replaces the demo gif in the readme to a new example that showcases features such as custom emojis and embeds.
Old
New
=> docs(readme): Replaces the demo gif using embeds

nextcord/ext/menus/menu_pages.py
Currently, when doing list pagination, reaction menus do not show any reactions if there is only 1 page to display.
This brings the same functionality to Button menus.
=> fix: Don't show pagination buttons if only 1 page

nextcord/ext/menus/__init__.py, nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/page_source.py
This is a hotfix to 1.3.3 where AsyncIteratorPageSource stopped working due to #24 
Note:
When using AsyncIteratorPageSource when there is only 1 page, the buttons get displayed for a split second before they get removed in start(). This is an extremely rare use case, but should be mentioned regardless.
=> fix: AsyncIterator buttons not getting displayed

docs/ext/menus/menu_examples.rst, docs/ext/menus/pagination_examples.rst, nextcord/ext/menus/__init__.py, nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/menus.py
Fixes #26 
This PR allows menus to be sent in response to an interaction such as components and slash commands.
Differences between menus in message commands and slash commands:
`pages.start(interaction=interaction)` will be used in place of `pages.start(ctx)`
Ephemeral responses:
```py
pages.start(interaction=interaction, ephemeral=True)
```
(Note: reaction menus cannot be send with ephemeral due to a Discord limitation)
Sending an initial message with interaction response:
```py
await self.interaction.response.send_message(**kwargs)
return await self.interaction.original_message()
```
----
This version (1.4.0) can be tested early with
```
pip install -U git+https://github.com/DenverCoderOne/nextcord-ext-menus@interaction-response#egg=nextcord-ext-menus
```
=> feat: Support for menu in interaction response

nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/menus.py
The current implementation of `MenuPages` uses `interaction.response.send_message` to send the initial message which does not work if `defer` was used beforehand.
This changes the implementation to use the helper function `Interaction.send` so that it will work even if `defer` was used beforehand.
---
Can be tested with:
```
pip install -U git+https://github.com/DenverCoderOne/nextcord-ext-menus@pages-defer --force-reinstall
```
=> feat: support send pages after defer

docs/ext/menus/reaction_menus.rst, nextcord/ext/menus/constants.py, nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/page_source.py
Resolves #29 
Previously a dict containing `{ "embeds": embeds }` would have to be returned in `format_page` to send multiple embeds. This simplifies the usage by allowing the user to simply return the list of embeds.
Example:
```py
class MultipleEmbeds(menus.ListPageSource):
def __init__(self, data):
super().__init__(data, per_page=3)
async def format_page(self, menu, entries):
embeds = []
for entry in entries:
embed = nextcord.Embed(title="Entries", description=entry)
embeds.append(embed)
return embeds
@bot.slash_command(guild_ids=[TESTING_GUILD_ID], name="beds")
async def button_multiple_embed_description(interaction):
data = [f"Description for entry #{num}" for num in range(1, 51)]
pages = menus.ButtonMenuPages(source=MultipleEmbeds(data))
await pages.start(interaction=interaction) …
```
=> feat: support format_page returning list of embeds

nextcord/ext/menus/menu_pages.py
**Problem:**
`should_add_reactions` is returning true for `MenuPages` when there are no reactions. This makes it check for reactions permissions when it does not need to.
**Solution:**
* `MenuPages.should_add_reactions_or_buttons()` now uses the implementation of `Menu` by returning `self.should_add_reactions() or self.should_add_buttons()`.
* `MenuPages.should_add_reactions()` and `MenuPages.should_add_buttons()` now call their respective super() implementations in addition to checking if paginating.
* In `ButtonMenuPages`, `should_add_buttons()` is overridden to only check if the source is paginating since buttons are added in the constructor and `should_add_buttons()` is checked in the constructor before the buttons are added.
=> fix: should_add_reactions returning true for Button menu

nextcord/ext/menus/page_source.py
Given this method appears to be used for both reactions *and* buttons, this change makes sense.
=> Clean up page source docstring

examples/embed_pages.py, nextcord/ext/menus/menus.py
Essentially the current implementation doesn't check if the user (bot) can send messages in a thread correctly. 
This change means if the channel is a thread we check the thread send permissions rather than parent channel permissions. Think for example next cord help threads
Close #28
=> fix: permissions checks for threads

docs/ext/menus/api.rst, docs/ext/menus/reaction_menus.rst, nextcord/ext/menus/constants.py, nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/page_source.py
1. Fixed rst List documentation from :class:\`List[nextcord.Embed]\` to List[:class:\`nextcord.Embed\`] for proper linking.
2. Documented the type of `page` in `ListPageSource.format_page` and `AsyncIteratorPageSource.format_page`
3. Renamed `_GroupByEntry` named tuple to `GroupByEntry` and documented the class.
4. Change type of `SendKwargsType` to allow any type to appear in the send kwargs returned by `format_page`. This includes files, stickers, bool, AllowedMentions, etc. to be passed in the kwargs dict.
=> Refactor type annotations and documentation

nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/menus.py
There is a small issue with AsyncIterator page sources where if a menu requires only 1 page, the buttons will be created but then removed within a second. This happens because `is_paginating` is not able to determine if more than 1 page is needed until the first page is read. This will also apply to any custom page sources where the former applies. Currently the buttons are cleared in `start()`, after the menu has been sent.
This PR makes it so that the buttons are removed from the view after the page is read, but **before** it is sent so that it doesn't need to be edited afterwards.
Additionally, `ButtonMenu.clear()` was updated to only remove `nextcord.ui.Button` objects. This was done since it is what is already written in the docstring and is consistent with `disable()` and …
=> fix: Clear buttons before sending if one page async iterator source

nextcord/ext/menus/menu_pages.py, nextcord/ext/menus/menus.py, requirements.txt
If there are reaction buttons, the full InteractionMessage must be fetched when send returns a PartialInteractionMessage.
PartialInteractionMessage does not support add_reactions, so it should not be returned when self.buttons contains elements.
This was working prior to nextcord 2.0.0b1 due to a statement that was intended to be future-proof:
```py
message = await self.interaction.send(ephemeral=self.ephemeral, **kwargs)
return message or await self.interaction.original_message()
```
As prior to 2.0.0b1, `message` would always be `None`, this worked fine. When using nextcord 2.0.0b1 or later, this does not work for reaction menus.
**BREAKING CHANGE**
As this module now uses `nextcord.PartialInteractionMessage` in type checks, nextcord >= 2.0.0b1 is now required to run the module. When …
=> fix: Adding reactions to interaction response in menu pages

nextcord/ext/menus/menus.py
Bots can send interaction responses even when the Send Messages permission is not enabled.
Bots can also send embeds even when Embed Links permission is not enabled.
This skips the check for the permission if an interaction is used instead of ctx.
=> fix: Prevent CannotSendMessages or CannotEmbedLinks on interaction

nextcord/ext/menus/menus.py
Fixes pyright error
```py
/home/runner/work/nextcord-ext-menus/nextcord-ext-menus/nextcord/ext/menus/menus.py
/home/runner/work/nextcord-ext-menus/nextcord-ext-menus/nextcord/ext/menus/menus.py:506:47 - error: Cannot access member "id" for type "PartialInteractionMessage"
Member "id" is unknown (reportGeneralTypeIssues)
```
Reaction Menus require a Message object which is asserted elsewhere in the code, so if `self.message` is a `PartialInteractionMessage` or `None`, we don't need to check the reactions.
=> refactor: fix pyright issue with message.id

nextcord/ext/menus/menu_pages.py
Specifying `channel` in `MenuPages.start()` gets ignored when `interaction` is passed instead of `ctx`.
If `channel` is specified to be a channel other than the interaction channel, `channel.send` will be used instead of `interaction.send`.
Note: In this situation, the user should be sending an interaction response before starting the menu.
```py
@bot.slash_command()
async def interaction_channel_example(interaction: Interaction, channel: nextcord.TextChannel):
await interaction.send(f"Your menu will appear in {channel.mention}", ephemeral=True)
pages = menus.ButtonMenuPages(source=MySource([f"Entry {i}" for i in range(1, 21)]))
await pages.start(interaction=interaction, channel=channel)
```
=> fix: Use channel if overridden in start with interaction

docs/_static/css/custom.css, docs/_static/js/toggleDarkMode.js, setup.py
The dark mode toggle was not appearing in the latest version of the docs due to changes in the class names for sphinx book theme.
This updates my toggleDarkMode script to use the correct class name for adding the dark mode toggle to the header, makes it consistent with the new HTML structure, and updates the dependency to be *fixed* at 0.3.3.
=> docs: Fix dark mode toggle for new sphinx book theme

docs/ext/menus/api.rst, setup.py
GroupByEntry was showing duplicate entries for `key` and `items` in Sphinx 5.x.
This fixes the issue by removing `:members:` (Thanks https://stackoverflow.com/a/63637956/11608064)
=> docs: Fix duplicate members in GroupByEntry

nextcord/ext/menus/menus.py
Fixes https://discord.com/channels/881118111967883295/1132658144133255178 (`#ext-menus (deesiigneer#0)`)
`Interaction.channel` is of type `PartialMessageable` when the channel is a DM channel which causes an error when trying to call `channel.permissions_for(me)`.
To fix this, we can use `interaction.app_permissions` whenever it is available.
This also adds support for passing a `PartialMessageable` as the `channel` parameter by assuming all permissions.
----
Test package early with:
`pip install git+https://github.com/nextcord/nextcord-ext-menus.git@0ff6f0b33955bf3231f734642dad617d9d494c18#egg=nextcord-ext-menus`
=> fix: Permissions error with interaction menus in DM channels
